### PR TITLE
fix: update _dragEventsChanged to check for marker instead of map

### LINKED ISSUE #7: google-map-marker: update if condition in _dragEventsChanged method to check for marker instead of map
While working on GoogleMaps issue [#40](https://github.com/FlowingCode/GoogleMapsAddon/issues/40) I run into a JS error _"__**Uncaught TypeError: Cannot read property '__e3_' of undefined**__"_ issue when trying to add a listener for _**google-map-marker-dragend**_ event. After some debugging I found that the issue is in **google-map-marker.js** file, in method ```_dragEventsChanged()```. The if condition should be ```if(this.marker)``` instead of ```if(this.map)```. If marker is undefined at this point there should be no call to ```this._forwardEvent('dragend');``` that is what is making it fail.

### PR DESCRIPTION
**Pull request by paodb**
Close #7

### CODE REVIEW

**Review by mlopezFC — APPROVED** [review]
Good catch!

**Comment by paodb** [comment]
The same fix should be done on ```_clickEventsChanged()``` & ```_mouseEventsChanged()``` methods. Can I do that as part of this PR or should I create a new issue?

**Comment by mlopezFC** [comment]
> The same fix should be done on `_clickEventsChanged()` & `_mouseEventsChanged()` methods. Can I do that as part of this PR or should I create a new issue? @mlopezFC

Yes, let's use this PR for that

**Comment by paodb** [comment]
Branch updated.

**Pull request merged**
